project:
  type: website
  output-dir: _site

website:
  title: "Rahul Garud"
  description: "Public finance • Fiscal policy • Debt sustainability"
  site-url: "https://garud-rd.github.io"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "Blog"
        href: blog/index.qmd
      - text: "Research"
        href: research/index.qmd
      - text: "Talks"
        href: talks/index.qmd
      - text: "CV"
        href: cv/index.qmd
    right:
      - icon: linkedin
        href: "https://www.linkedin.com/in/garudrd/"
      - icon: envelope
        href: "mailto:garudrd@gmail.com"

format:
  html:
    theme: cosmo
    toc: true
    page-layout: full
    smooth-scroll: true
